name: Update Readme Image
on:
  workflow_dispatch:
  schedule:
    # Runs every day
    - cron: '0 0 * * *'
    

jobs:
  update-readme:
    name: Update Image README
    runs-on: ubuntu-latest
    steps:
      - uses: siddharth2016/update-readme-image@main
        with:
          HEIGHT: 550px
          WIDTH: 850px
          ALIGN: center
          IMG_ALT: Daily Readme Image
