name: Update blog posts
on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    # Runs every sunday
    - cron: '0 0 * * 0'
    

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: DEVTO
          feed_list: "https://dev.to/feed/zohebabai"
